In [1]:
# Import necessary libraries
import numpy as np
import scipy.ndimage as ndi
import matplotlib.pyplot as plt

In [2]:
# Example 1: Creating a 1D array with NumPy and SciPy
characters = np.array(['Jon Snow', 'Daenerys Targaryen', 'Tyrion Lannister'])
print("Example 1: 1D Array of Characters:", characters)

Example 1: 1D Array of Characters: ['Jon Snow' 'Daenerys Targaryen' 'Tyrion Lannister']


In [3]:
# Example 2: Creating a 2D array with NumPy and SciPy
houses = np.array([
    ['Stark', 'Tully', 'Baratheon'],
    ['Targaryen', 'Lannister', 'Greyjoy']
])
print("Example 2: 2D Array of Houses:", houses)

Example 2: 2D Array of Houses: [['Stark' 'Tully' 'Baratheon']
 ['Targaryen' 'Lannister' 'Greyjoy']]


In [4]:
# Example 3: Creating a 3D array with NumPy and SciPy
kingdoms = np.array([
    [['North', 'Riverlands'], ['Stormlands', 'Crownlands']],
    [['Dragonstone', 'Westerlands'], ['Iron Islands', 'Reach']]
])
print("Example 3: 3D Array of Kingdoms:", kingdoms)

Example 3: 3D Array of Kingdoms: [[['North' 'Riverlands']
  ['Stormlands' 'Crownlands']]

 [['Dragonstone' 'Westerlands']
  ['Iron Islands' 'Reach']]]


In [5]:
# Example 4: Accessing elements of a multi-dimensional array
print("Example 4: Accessing element [1, 2] of houses:", houses[1, 2])

Example 4: Accessing element [1, 2] of houses: Greyjoy


In [6]:
# Example 5: Slicing a multi-dimensional array
print("Example 5: Slicing elements from houses:", houses[:, 1:])

Example 5: Slicing elements from houses: [['Tully' 'Baratheon']
 ['Lannister' 'Greyjoy']]


In [7]:

# Example 6: Shape of a multi-dimensional array
print("Example 6: Shape of kingdoms array:", kingdoms.shape)

Example 6: Shape of kingdoms array: (2, 2, 2)


In [8]:
# Example 7: Reshaping a multi-dimensional array
reshaped_kingdoms = kingdoms.reshape((2, 4))
print("Example 7: Reshaped kingdoms array:", reshaped_kingdoms)

Example 7: Reshaped kingdoms array: [['North' 'Riverlands' 'Stormlands' 'Crownlands']
 ['Dragonstone' 'Westerlands' 'Iron Islands' 'Reach']]


In [9]:
# Example 8: Transposing a multi-dimensional array
transposed_houses = houses.T
print("Example 8: Transposed houses array:", transposed_houses)

Example 8: Transposed houses array: [['Stark' 'Targaryen']
 ['Tully' 'Lannister']
 ['Baratheon' 'Greyjoy']]


In [10]:
# Example 9: Element-wise operations on multi-dimensional arrays
ages = np.array([
    [35, 24, 42],
    [27, 38, 19]
])

birth_years = 300 - ages
print("Example 9: Birth years of characters:", birth_years)

Example 9: Birth years of characters: [[265 276 258]
 [273 262 281]]


In [11]:
# Example 10: Matrix multiplication with multi-dimensional arrays
house_population = np.array([1000, 800, 1200])
house_resources = np.array([500, 400, 600])
total_resources = np.dot(house_population, house_resources)
print("Example 10: Total resources in the kingdom:", total_resources)

Example 10: Total resources in the kingdom: 1540000


In [12]:
# Example 11: Element-wise comparison on multi-dimensional arrays
traitors = np.array([
    [False, True, False],
    [True, False, False]
])

enemies = np.array([
    [False, True, True],
    [True, False, True]
])

war_status = np.logical_and(traitors, enemies)
print("Example 11: War status with traitors and enemies:", war_status)

Example 11: War status with traitors and enemies: [[False  True False]
 [ True False False]]


In [13]:
# Example 12: Broadcasting in multi-dimensional arrays
wildlings = np.array([10000, 8000, 12000])
wildlings_ratio = wildlings[:, np.newaxis] / house_population
print("Example 12: Wildlings to House population ratio:", wildlings_ratio)

Example 12: Wildlings to House population ratio: [[10.         12.5         8.33333333]
 [ 8.         10.          6.66666667]
 [12.         15.         10.        ]]


In [14]:
# Example 13: Reduction operations on multi-dimensional arrays
total_wildlings = np.sum(wildlings)
print("Example 13: Total number of wildlings:", total_wildlings)

Example 13: Total number of wildlings: 30000


In [15]:
# Example 14: Stacking arrays vertically
kingsguard1 = np.array(['Jaime Lannister', 'Sandor Clegane'])
kingsguard2 = np.array(['Barristan Selmy', 'Arthur Dayne'])
all_kingsguard = np.vstack((kingsguard1, kingsguard2))
print("Example 14: All Kingsguard members:", all_kingsguard)

Example 14: All Kingsguard members: [['Jaime Lannister' 'Sandor Clegane']
 ['Barristan Selmy' 'Arthur Dayne']]


In [16]:
# Example 15: Stacking arrays horizontally
maesters1 = np.array(['Aemon', 'Pycelle'])
maesters2 = np.array(['Qyburn', 'Luwin'])
all_maesters = np.hstack((maesters1, maesters2))
print("Example 15: All Maesters:", all_maesters)

Example 15: All Maesters: ['Aemon' 'Pycelle' 'Qyburn' 'Luwin']


In [17]:
# Example 16: Splitting arrays
houses_split = np.hsplit(houses, 3)
print("Example 16: Split houses array:", houses_split)

Example 16: Split houses array: [array([['Stark'],
       ['Targaryen']], dtype='<U9'), array([['Tully'],
       ['Lannister']], dtype='<U9'), array([['Baratheon'],
       ['Greyjoy']], dtype='<U9')]


In [18]:
# Example 17: Repeating elements in a multi-dimensional array
repeat_houses = np.repeat(houses, 2, axis=0)
print("Example 17: Repeating houses array:", repeat_houses)

Example 17: Repeating houses array: [['Stark' 'Tully' 'Baratheon']
 ['Stark' 'Tully' 'Baratheon']
 ['Targaryen' 'Lannister' 'Greyjoy']
 ['Targaryen' 'Lannister' 'Greyjoy']]


In [19]:
# Example 18: Tiling elements in a multi-dimensional array
tile_kingdoms = np.tile(kingdoms, (2, 1, 1))
print("Example 18: Tiled kingdoms array:", tile_kingdoms)

Example 18: Tiled kingdoms array: [[['North' 'Riverlands']
  ['Stormlands' 'Crownlands']]

 [['Dragonstone' 'Westerlands']
  ['Iron Islands' 'Reach']]

 [['North' 'Riverlands']
  ['Stormlands' 'Crownlands']]

 [['Dragonstone' 'Westerlands']
  ['Iron Islands' 'Reach']]]


In [20]:
# Example 19: Flattening a multi-dimensional array
flattened_kingdoms = kingdoms.flatten()
print("Example 19: Flattened kingdoms array:", flattened_kingdoms)

Example 19: Flattened kingdoms array: ['North' 'Riverlands' 'Stormlands' 'Crownlands' 'Dragonstone'
 'Westerlands' 'Iron Islands' 'Reach']


In [21]:
# Example 20: Raveling a multi-dimensional array
raveled_kingdoms = kingdoms.ravel()
print("Example 20: Raveled kingdoms array:", raveled_kingdoms)

Example 20: Raveled kingdoms array: ['North' 'Riverlands' 'Stormlands' 'Crownlands' 'Dragonstone'
 'Westerlands' 'Iron Islands' 'Reach']


In [22]:
# Example 21: Iterating over multi-dimensional arrays
for house in np.nditer(houses):
    print("Example 21: House:", house)

Example 21: House: Stark
Example 21: House: Tully
Example 21: House: Baratheon
Example 21: House: Targaryen
Example 21: House: Lannister
Example 21: House: Greyjoy


In [23]:
# Example 22: Broadcasting arrays to the same shape
wildlings_population = np.broadcast_to(wildlings, (2, 3))
print("Example 22: Broadcasted wildlings population array:", wildlings_population)


Example 22: Broadcasted wildlings population array: [[10000  8000 12000]
 [10000  8000 12000]]


In [24]:
# Example 23: Element-wise functions on multi-dimensional arrays
health_points = np.array([
    [100, 90, 80],
    [70, 60, 50]
])

# Use NumPy's vectorized functions on the health_points array
damage = np.sqrt(health_points)
print("Example 23: Damage points after an attack:", damage)

Example 23: Damage points after an attack: [[10.          9.48683298  8.94427191]
 [ 8.36660027  7.74596669  7.07106781]]


```python
# Example 24: Convolution using 2D array (Image Blurring)
# Load an image using matplotlib and convert it to a grayscale 2D array
image = plt.imread('game_of_thrones.jpg')
gray_image = np.mean(image, axis=-1)

# Create a kernel for image blurring
kernel = np.ones((5, 5)) / 25

# Use scipy's ndimage.convolve function to apply the kernel and blur the image
blurred_image = ndi.convolve(gray_image, kernel)

# Plot the original and blurred images
plt.figure(figsize=(10, 6))
plt.subplot(1, 2, 1)
plt.imshow(gray_image, cmap='gray')
plt.title('Original Image')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(blurred_image, cmap='gray')
plt.title('Blurred Image')
plt.axis('off')

plt.show()
```




```python
# Example 25: Downsampling using 2D array (Image Downscaling)
# Use scipy's ndimage.zoom function to downscale the original image
downscaled_image = ndi.zoom(image, (0.5, 0.5, 1))

# Plot the original and downscaled images
plt.figure(figsize=(10, 6))
plt.subplot(1, 2, 1)
plt.imshow(image)
plt.title('Original Image')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(downscaled_image)
plt.title('Downscaled Image')
plt.axis('off')

plt.show()
```