In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

In [2]:
# Example 1: Matrix Addition
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = A + B
print("Matrix Addition Result:")
print(result)

Matrix Addition Result:
[[ 6  8]
 [10 12]]


In [3]:
# Example 2: Matrix Subtraction
result = A - B
print("Matrix Subtraction Result:")
print(result)

Matrix Subtraction Result:
[[-4 -4]
 [-4 -4]]


In [4]:
# Example 3: Matrix Multiplication
result = np.dot(A, B)
print("Matrix Multiplication Result:")
print(result)

Matrix Multiplication Result:
[[19 22]
 [43 50]]


In [5]:
# Example 4: Matrix Transpose
result = A.T
print("Matrix Transpose:")
print(result)

Matrix Transpose:
[[1 3]
 [2 4]]


In [6]:
# Example 5: Matrix Determinant
det_A = la.det(A)
print("Determinant of Matrix A:")
print(det_A)

Determinant of Matrix A:
-2.0


In [7]:
# Example 6: Matrix Inversion
A_inv = la.inv(A)
print("Inverse of Matrix A:")
print(A_inv)

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [8]:
# Example 7: Matrix Rank
rank_A = la.matrix_rank(A)
print("Rank of Matrix A:")
print(rank_A)

AttributeError: module 'scipy.linalg' has no attribute 'matrix_rank'

In [9]:
# Example 8: LU Decomposition
P, L, U = la.lu(A)
print("LU Decomposition - P:")
print(P)
print("LU Decomposition - L:")
print(L)
print("LU Decomposition - U:")
print(U)

LU Decomposition - P:
[[0. 1.]
 [1. 0.]]
LU Decomposition - L:
[[1.         0.        ]
 [0.33333333 1.        ]]
LU Decomposition - U:
[[3.         4.        ]
 [0.         0.66666667]]


In [10]:
# Example 9: QR Decomposition
Q, R = la.qr(A)
print("QR Decomposition - Q:")
print(Q)
print("QR Decomposition - R:")
print(R)

QR Decomposition - Q:
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
QR Decomposition - R:
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [11]:
# Example 10: Cholesky Decomposition
A = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
L = la.cholesky(A)
print("Cholesky Decomposition:")
print(L)

Cholesky Decomposition:
[[ 2.  6. -8.]
 [ 0.  1.  5.]
 [ 0.  0.  3.]]


In [12]:
# Example 11: Eigenvalues and Eigenvectors
A = np.array([[1, 2], [2, 3]])
eigenvalues, eigenvectors = la.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[-0.23606798+0.j  4.23606798+0.j]
Eigenvectors:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]
