In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

In [2]:
# Example 1: Matrix Addition
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = A + B
print("Matrix Addition Result:")
print(result)

Matrix Addition Result:
[[ 6  8]
 [10 12]]


In [3]:
# Example 2: Matrix Subtraction
result = A - B
print("Matrix Subtraction Result:")
print(result)

Matrix Subtraction Result:
[[-4 -4]
 [-4 -4]]


In [4]:
# Example 3: Matrix Multiplication
result = np.dot(A, B)
print("Matrix Multiplication Result:")
print(result)

Matrix Multiplication Result:
[[19 22]
 [43 50]]


In [5]:
# Example 4: Matrix Transpose
result = A.T
print("Matrix Transpose:")
print(result)

Matrix Transpose:
[[1 3]
 [2 4]]


In [6]:
# Example 5: Matrix Determinant
det_A = la.det(A)
print("Determinant of Matrix A:")
print(det_A)

Determinant of Matrix A:
-2.0


In [7]:
# Example 6: Matrix Inversion
A_inv = la.inv(A)
print("Inverse of Matrix A:")
print(A_inv)

Inverse of Matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [8]:
# Example 7: Matrix Rank
rank_A = la.matrix_rank(A)
print("Rank of Matrix A:")
print(rank_A)

AttributeError: module 'scipy.linalg' has no attribute 'matrix_rank'

In [9]:
# Example 8: LU Decomposition
P, L, U = la.lu(A)
print("LU Decomposition - P:")
print(P)
print("LU Decomposition - L:")
print(L)
print("LU Decomposition - U:")
print(U)

LU Decomposition - P:
[[0. 1.]
 [1. 0.]]
LU Decomposition - L:
[[1.         0.        ]
 [0.33333333 1.        ]]
LU Decomposition - U:
[[3.         4.        ]
 [0.         0.66666667]]


In [10]:
# Example 9: QR Decomposition
Q, R = la.qr(A)
print("QR Decomposition - Q:")
print(Q)
print("QR Decomposition - R:")
print(R)

QR Decomposition - Q:
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
QR Decomposition - R:
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [11]:
# Example 10: Cholesky Decomposition
A = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
L = la.cholesky(A)
print("Cholesky Decomposition:")
print(L)

Cholesky Decomposition:
[[ 2.  6. -8.]
 [ 0.  1.  5.]
 [ 0.  0.  3.]]


In [12]:
# Example 11: Eigenvalues and Eigenvectors
A = np.array([[1, 2], [2, 3]])
eigenvalues, eigenvectors = la.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[-0.23606798+0.j  4.23606798+0.j]
Eigenvectors:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [13]:
# Example 12: Solving a Linear System
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 8])
x = la.solve(A, b)
print("Solution of Linear System:")
print(x)

Solution of Linear System:
[1.4 2.2]


In [14]:
# Example 13: Matrix Power
A = np.array([[1, 2], [2, 3]])
A_power = la.matrix_power(A, 3)
print("Matrix Power (A^3):")
print(A_power)

AttributeError: module 'scipy.linalg' has no attribute 'matrix_power'

In [15]:
# Example 14: Singular Value Decomposition (SVD)
A = np.array([[1, 2], [3, 4], [5, 6]])
U, S, Vh = la.svd(A)
print("SVD - U:")
print(U)
print("SVD - S:")
print(S)
print("SVD - Vh:")
print(Vh)

SVD - U:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
SVD - S:
[9.52551809 0.51430058]
SVD - Vh:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [16]:
# Example 15: Moore-Penrose Pseudoinverse
A = np.array([[1, 2, 3], [4, 5, 6]])
A_pinv = la.pinv(A)
print("Moore-Penrose Pseudoinverse:")
print(A_pinv)

Moore-Penrose Pseudoinverse:
[[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]


In [17]:
# Example 16: Matrix Exponential
A = np.array([[1, 2], [2, 3]])
A_exp = la.expm(A)
print("Matrix Exponential:")
print(A_exp)

Matrix Exponential:
[[19.68002699 30.56514746]
 [30.56514746 50.24517445]]


In [18]:
# Example 17: Kronecker Product
A = np.array([[1, 2], [3, 4]])
B = np.array([[0, 5], [6, 7]])
kronecker_product = np.kron(A, B)
print("Kronecker Product:")
print(kronecker_product)

Kronecker Product:
[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]


In [19]:
# Example 18: Block Diagonal Matrix
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
block_diag_matrix = la.block_diag(A, B)
print("Block Diagonal Matrix:")
print(block_diag_matrix)

Block Diagonal Matrix:
[[1 2 0 0]
 [3 4 0 0]
 [0 0 5 6]
 [0 0 7 8]]


In [20]:
# Example 19: Trace of a Matrix
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
trace_A = np.trace(A)
print("Trace of Matrix A:")
print(trace_A)

Trace of Matrix A:
15


In [21]:
# Example 20: Symmetric Positive Definite Matrix
A = np.array([[5, -1], [-1, 2]])
is_spd = la.cholesky_banded(A)
print("Is A Symmetric Positive Definite?")
print(is_spd)

LinAlgError: 1-th leading minor not positive definite

In [22]:
# Example 21: Matrix Condition Number
A = np.array([[1, 2], [3, 4]])
cond_num_A = la.cond(A)
print("Condition Number of Matrix A:")
print(cond_num_A)

AttributeError: module 'scipy.linalg' has no attribute 'cond'

In [23]:
# Example 22: Generalized Eigenvalues
A = np.array([[1, 2], [2, 3]])
B = np.array([[2, 0], [0, 1]])
eigenvalues, eigenvectors = la.eig(A, B)
print("Generalized Eigenvalues:")
print(eigenvalues)
print("Generalized Eigenvectors:")
print(eigenvectors)

Generalized Eigenvalues:
[-0.13745861+0.j  3.63745861+0.j]
Generalized Eigenvectors:
[[ 0.84324302  0.3036773 ]
 [-0.53753252  0.95277495]]
