In [1]:
import numpy as np
import scipy.sparse as sp

In [2]:
# Example 1: Creating a Sparse Matrix from Dense Matrix
dense_matrix = np.array([[1, 0, 0], [0, 0, 2], [3, 0, 0]])
sparse_matrix = sp.csr_matrix(dense_matrix)
print("Sparse Matrix:")
print(sparse_matrix)

Sparse Matrix:
  (0, 0)	1
  (1, 2)	2
  (2, 0)	3


In [3]:
# Example 2: Creating a Sparse Identity Matrix
sparse_identity = sp.eye(5)
print("Sparse Identity Matrix:")
print(sparse_identity)

Sparse Identity Matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0


In [4]:
# Example 3: Creating a Sparse Diagonal Matrix
diagonal_values = [1, 2, 3]
sparse_diagonal = sp.diags(diagonal_values, offsets=0)
print("Sparse Diagonal Matrix:")
print(sparse_diagonal)

Sparse Diagonal Matrix:
  (0, 0)	1.0
  (1, 1)	2.0
  (2, 2)	3.0


In [5]:
# Example 4: Creating a Sparse Random Matrix
random_sparse = sp.random(5, 5, density=0.3, format='csr')
print("Random Sparse Matrix:")
print(random_sparse)

Random Sparse Matrix:
  (0, 2)	0.030561132272335922
  (0, 3)	0.8321202144737638
  (1, 0)	0.9656077711805837
  (1, 2)	0.36248466252781975
  (2, 1)	0.8093611016278587
  (2, 4)	0.017521326714104335
  (3, 0)	0.38924652239360624
  (4, 3)	0.8710197437755582


In [6]:
# Example 5: Accessing Elements in a Sparse Matrix
element = sparse_matrix[2, 0]
print("Element at (2, 0):", element)

Element at (2, 0): 3


In [7]:
# Example 6: Converting Sparse Matrix to Dense Matrix
dense_matrix = sparse_matrix.toarray()
print("Dense Matrix:")
print(dense_matrix)

Dense Matrix:
[[1 0 0]
 [0 0 2]
 [3 0 0]]


In [8]:
# Example 7: Matrix Multiplication with Sparse Matrices
matrix_A = sp.random(3, 3, density=0.3, format='csr')
matrix_B = sp.random(3, 3, density=0.3, format='csr')
result = matrix_A.dot(matrix_B)
print("Matrix A:")
print(matrix_A.toarray())
print("Matrix B:")
print(matrix_B.toarray())
print("Result of Matrix Multiplication:")
print(result.toarray())


Matrix A:
[[0.         0.16680798 0.        ]
 [0.         0.78039846 0.        ]
 [0.29244626 0.         0.        ]]
Matrix B:
[[0.         0.67325909 0.        ]
 [0.68834436 0.         0.72358929]
 [0.         0.         0.        ]]
Result of Matrix Multiplication:
[[0.11482134 0.         0.12070047]
 [0.53718288 0.         0.56468797]
 [0.         0.19689211 0.        ]]


In [9]:
# Example 8: Matrix Addition with Sparse Matrices
matrix_C = sp.random(3, 3, density=0.3, format='csr')
result_addition = matrix_A + matrix_C
print("Matrix C:")
print(matrix_C.toarray())
print("Result of Matrix Addition:")
print(result_addition.toarray())

Matrix C:
[[0.         0.50042578 0.        ]
 [0.         0.25589401 0.        ]
 [0.02167808 0.         0.        ]]
Result of Matrix Addition:
[[0.         0.66723377 0.        ]
 [0.         1.03629247 0.        ]
 [0.31412434 0.         0.        ]]


In [10]:
# Example 9: Scalar Multiplication with Sparse Matrix
scalar = 2
result_scalar_mul = scalar * matrix_A
print("Scalar Multiplication Result:")
print(result_scalar_mul.toarray())

Scalar Multiplication Result:
[[0.         0.33361597 0.        ]
 [0.         1.56079692 0.        ]
 [0.58489253 0.         0.        ]]


In [11]:
# Example 10: Transpose of Sparse Matrix
result_transpose = matrix_A.T
print("Transpose of Matrix A:")
print(result_transpose.toarray())

Transpose of Matrix A:
[[0.         0.         0.29244626]
 [0.16680798 0.78039846 0.        ]
 [0.         0.         0.        ]]


In [12]:
# Example 11: Element-wise Matrix Multiplication (Hadamard Product)
matrix_D = sp.random(3, 3, density=0.3, format='csr')
result_elementwise_mul = matrix_A.multiply(matrix_D)
print("Matrix D:")
print(matrix_D.toarray())
print("Element-wise Matrix Multiplication Result:")
print(result_elementwise_mul.toarray())

Matrix D:
[[0.57792443 0.         0.        ]
 [0.09236912 0.40626038 0.        ]
 [0.         0.         0.        ]]
Element-wise Matrix Multiplication Result:
[[0.         0.         0.        ]
 [0.         0.31704497 0.        ]
 [0.         0.         0.        ]]


In [13]:
# Example 12: Finding Non-zero Elements in Sparse Matrix
nonzero_elements = matrix_A.nonzero()
print("Non-zero Elements:")
print(nonzero_elements)

Non-zero Elements:
(array([0, 1, 2]), array([1, 1, 0]))


In [14]:
# Example 13: Computing Sum of Elements in Sparse Matrix
sum_elements = matrix_A.sum()
print("Sum of Elements:", sum_elements)

Sum of Elements: 1.239652708170106


In [15]:
# Example 14: Counting Non-zero Elements in Sparse Matrix
count_nonzero = matrix_A.count_nonzero()
print("Number of Non-zero Elements:", count_nonzero)

Number of Non-zero Elements: 3


In [16]:
# Example 15: Finding Minimum and Maximum Elements in Sparse Matrix
min_element = matrix_A.min()
max_element = matrix_A.max()
print("Minimum Element:", min_element)
print("Maximum Element:", max_element)

Minimum Element: 0.0
Maximum Element: 0.7803984609775805
