In [29]:
import numpy as np
import scipy.linalg as linalg
import scipy.sparse.linalg as sparse_linalg
import scipy

In [2]:
# Example 1: Matrix Inversion using LU Decomposition
A = np.array([[1, 2], [3, 4]])
B = linalg.inv(A)
print(f"Inverse of A:\n{B}")

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [3]:
# Example 2: LU Decomposition
P, L, U = linalg.lu(A)
print(f"P:\n{P}")
print(f"L:\n{L}")
print(f"U:\n{U}")

P:
[[0. 1.]
 [1. 0.]]
L:
[[1.         0.        ]
 [0.33333333 1.        ]]
U:
[[3.         4.        ]
 [0.         0.66666667]]


In [4]:
# Example 3: QR Decomposition
Q, R = linalg.qr(A)
print(f"Q:\n{Q}")
print(f"R:\n{R}")

Q:
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R:
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [5]:
# Example 4: Singular Value Decomposition (SVD)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
U, s, Vh = linalg.svd(A)
print(f"U:\n{U}")
print(f"Singular Values:\n{s}")
print(f"Vh:\n{Vh}")


U:
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Singular Values:
[1.68481034e+01 1.06836951e+00 4.41842475e-16]
Vh:
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [6]:
# Example 5: Solving Linear System using LU Decomposition
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 11])
x = linalg.solve(A, b)
print(f"x:\n{x}")

x:
[1. 2.]


In [7]:
# Example 6: Solving Linear System using QR Decomposition
Q, R = linalg.qr(A)
b = np.array([5, 11])
y = np.dot(Q.T, b)
x = linalg.solve_triangular(R, y)
print(f"x:\n{x}")

x:
[1. 2.]


In [8]:
# Example 7: Iterative Solver (Conjugate Gradient Method)
A = np.array([[4, -1, 1], [-1, 4, -2], [1, -2, 3]])
b = np.array([6, 3, 4])
x, _ = sparse_linalg.cg(A, b)
print(f"x:\n{x}")

x:
[1.48275862 2.31034483 2.37931034]


In [9]:
# Example 8: Iterative Solver (BiCGSTAB Method)
A = np.array([[4, -1, 1], [-1, 4, -2], [1, -2, 3]])
b = np.array([6, 3, 4])
x, _ = sparse_linalg.bicgstab(A, b)
print(f"x:\n{x}")


x:
[1.48275862 2.31034483 2.37931034]


In [16]:
# Example 9: Sparse Matrix Creation (CSC Format)
import scipy.sparse

rows = np.array([0, 1, 1, 2, 2, 2])
cols = np.array([0, 0, 1, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
A = linalg.csc_matrix((data, (rows, cols)), shape=(3, 3))
print(f"Sparse Matrix (CSC Format):\n{A.toarray()}")

AttributeError: module 'scipy.linalg' has no attribute 'csc_matrix'

In [11]:
# Example 10: Sparse Matrix Creation (COO Format)
rows = np.array([0, 1, 1, 2, 2, 2])
cols = np.array([0, 0, 1, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
A = linalg.coo_matrix((data, (rows, cols)), shape=(3, 3))
print(f"Sparse Matrix (COO Format):\n{A.toarray()}")

AttributeError: module 'scipy.linalg' has no attribute 'coo_matrix'

In [13]:
# Example 11: Sparse Matrix Creation (CSR Format)
rows = np.array([0, 1, 1, 2, 2, 2])
cols = np.array([0, 0, 1, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
A = linalg.csr_matrix((data, (rows, cols)), shape=(3, 3))
print(f"Sparse Matrix (CSR Format):\n{A.toarray()}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [14]:
# Example 12: Sparse Matrix Vector Multiplication
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
x = np.array([1, 2, 3])
b = A.dot(x)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector x: {x}")
print(f"Result of A*x: {b}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [15]:
# Example 13: Sparse Matrix Addition
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
B = linalg.csr_matrix([[3, 0, 1], [0, 2, 0], [2, 0, 4]])
C = A + B
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Sparse Matrix B:\n{B.toarray()}")
print(f"Result of A + B:\n{C.toarray()}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [17]:
# Example 14: Sparse Matrix Subtraction
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
B = linalg.csr_matrix([[3, 0, 1], [0, 2, 0], [2, 0, 4]])
C = A - B
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Sparse Matrix B:\n{B.toarray()}")
print(f"Result of A - B:\n{C.toarray()}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [18]:
# Example 15: Sparse Matrix Multiplication
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
B = linalg.csr_matrix([[3, 0, 1], [0, 2, 0], [2, 0, 4]])
C = A.dot(B)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Sparse Matrix B:\n{B.toarray()}")
print(f"Result of A * B:\n{C.toarray()}")


AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [19]:
# Example 16: Sparse Matrix Transpose
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
B = A.transpose()
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Sparse Matrix A Transpose:\n{B.toarray()}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [20]:
# Example 17: Sparse Matrix Inversion
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
A_inv = sparse_linalg.inv(A)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Inverse of A:\n{A_inv.toarray()}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [21]:
# Example 18: Sparse Matrix Determinant
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
det = sparse_linalg.det(A)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Determinant of A: {det}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [22]:
# Example 19: Sparse Matrix Eigenvectors and Eigenvalues
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
eigenvalues, eigenvectors = sparse_linalg.eigs(A, k=2)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Eigenvalues:\n{eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [23]:
# Example 20: Sparse Linear System Solver
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
b = np.array([1, 2, 3])
x = sparse_linalg.spsolve(A, b)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector b: {b}")
print(f"Solutions of Ax = b: {x}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [24]:
# Example 21: Sparse Matrix Tridiagonal System Solver
diagonals = [[1, 2, 3], [4, 5, 6, 7], [8, 9, 10]]
A = linalg.spdiags(diagonals, [-1, 0, 1], 4, 4)
b = np.array([1, 2, 3, 4])
x = sparse_linalg.spsolve(A, b)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector b: {b}")
print(f"Solutions of Ax = b: {x}")

AttributeError: module 'scipy.linalg' has no attribute 'spdiags'

In [25]:
# Example 22: Iterative Linear Solver for Sparse Matrix
A = linalg.csr_matrix([[4, -1, 0], [-1, 4, -1], [0, -1, 4]])
b = np.array([3, 4, 3])
x, _ = sparse_linalg.cg(A, b)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector b: {b}")
print(f"Solutions of Ax = b using CG: {x}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [26]:
# Example 23: Iterative Linear Solver for Sparse Matrix (BiCGSTAB)
A = linalg.csr_matrix([[4, -1, 0], [-1, 4, -1], [0, -1, 4]])
b = np.array([3, 4, 3])
x, _ = sparse_linalg.bicgstab(A, b)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector b: {b}")
print(f"Solutions of Ax = b using BiCGSTAB: {x}")


AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [27]:
# Example 24: Iterative Linear Solver for Sparse Matrix (GMRES)
A = linalg.csr_matrix([[4, -1, 0], [-1, 4, -1], [0, -1, 4]])
b = np.array([3, 4, 3])
x, _ = sparse_linalg.gmres(A, b)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector b: {b}")
print(f"Solutions of Ax = b using GMRES: {x}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [30]:
# Example 25: Iterative Linear Solver for Sparse Matrix (LGMRES)
A = linalg.csr_matrix([[4, -1, 0], [-1, 4, -1], [0, -1, 4]])
b = np.array([3, 4, 3])
x, _ = sparse_linalg.lgmres(A, b)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector b: {b}")
print(f"Solutions of Ax = b using LGMRES: {x}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [31]:
# Example 26: Cholesky Decomposition
A = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
L = linalg.cholesky(A)
print(f"A:\n{A}")
print(f"L (Cholesky Decomposition):\n{L}")

A:
[[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]
L (Cholesky Decomposition):
[[ 2.  6. -8.]
 [ 0.  1.  5.]
 [ 0.  0.  3.]]


In [32]:
# Example 27: Eigenvalue Decomposition (Eigendecomposition)
A = np.array([[2, -1], [-1, 3]])
eigenvalues, eigenvectors = linalg.eig(A)
print(f"A:\n{A}")
print(f"Eigenvalues:\n{eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

A:
[[ 2 -1]
 [-1  3]]
Eigenvalues:
[1.38196601+0.j 3.61803399+0.j]
Eigenvectors:
[[-0.85065081  0.52573111]
 [-0.52573111 -0.85065081]]


In [33]:
# Example 28: Schur Decomposition
A = np.array([[2, -1, 1], [0, 3, -2], [0, 0, 2]])
T, Q = linalg.schur(A)
print(f"A:\n{A}")
print(f"T (Schur Decomposition):\n{T}")
print(f"Q (Unitary matrix):\n{Q}")

A:
[[ 2 -1  1]
 [ 0  3 -2]
 [ 0  0  2]]
T (Schur Decomposition):
[[ 2. -1.  1.]
 [ 0.  3. -2.]
 [ 0.  0.  2.]]
Q (Unitary matrix):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
# Example 29: Singular Value Decomposition (SVD)
A = np.array([[1, 2], [3, 4], [5, 6]])
U, s, Vh = linalg.svd(A)
print(f"A:\n{A}")
print(f"U:\n{U}")
print(f"Singular Values:\n{s}")
print(f"Vh:\n{Vh}")

A:
[[1 2]
 [3 4]
 [5 6]]
U:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Singular Values:
[9.52551809 0.51430058]
Vh:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [35]:
# Example 30: Pseudoinverse
A = np.array([[1, 2], [3, 4], [5, 6]])
pinv_A = linalg.pinv(A)
print(f"A:\n{A}")
print(f"Pseudoinverse of A:\n{pinv_A}")

A:
[[1 2]
 [3 4]
 [5 6]]
Pseudoinverse of A:
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [36]:
# Example 31: Determinant
A = np.array([[1, 2], [3, 4]])
det = linalg.det(A)
print(f"A:\n{A}")
print(f"Determinant of A: {det}")

A:
[[1 2]
 [3 4]]
Determinant of A: -2.0


In [37]:
# Example 32: Matrix Rank
A = np.array([[1, 2], [3, 4], [5, 6]])
rank = linalg.matrix_rank(A)
print(f"A:\n{A}")
print(f"Rank of A: {rank}")

AttributeError: module 'scipy.linalg' has no attribute 'matrix_rank'

In [38]:
# Example 33: Matrix Power
A = np.array([[1, 2], [3, 4]])
power_A = linalg.matrix_power(A, 3)
print(f"A:\n{A}")
print(f"A^3 (Matrix Power):\n{power_A}")

AttributeError: module 'scipy.linalg' has no attribute 'matrix_power'

In [39]:
# Example 34: Matrix Exponential
A = np.array([[1, 2], [2, 3]])
exp_A = linalg.expm(A)
print(f"A:\n{A}")
print(f"e^A (Matrix Exponential):\n{exp_A}")

A:
[[1 2]
 [2 3]]
e^A (Matrix Exponential):
[[19.68002699 30.56514746]
 [30.56514746 50.24517445]]


In [40]:
# Example 35: Matrix Logarithm
A = np.array([[1, 2], [2, 3]])
log_A = linalg.logm(A)
print(f"A:\n{A}")
print(f"log(A) (Matrix Logarithm):\n{log_A}")

A:
[[1 2]
 [2 3]]
log(A) (Matrix Logarithm):
[[-0.64561341+2.2732778j   1.29122682-1.40496295j]
 [ 1.29122682-1.40496295j  0.64561341+0.86831485j]]


In [41]:
# Example 36: Kronecker Product
A = np.array([[1, 2], [3, 4]])
B = np.array([[0, 5], [6, 7]])
kronecker_A_B = linalg.kron(A, B)
print(f"A:\n{A}")
print(f"B:\n{B}")
print(f"Kronecker Product of A and B:\n{kronecker_A_B}")

A:
[[1 2]
 [3 4]]
B:
[[0 5]
 [6 7]]
Kronecker Product of A and B:
[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]


In [42]:
# Example 37: Identity Matrix
I = linalg.identity(3)
print(f"Identity Matrix (3x3):\n{I}")

AttributeError: module 'scipy.linalg' has no attribute 'identity'

In [43]:
# Example 38: Diagonal Matrix
diagonal = np.array([1, 2, 3])
D = linalg.diagsvd(diagonal, 3, 3)
print(f"Diagonal Matrix (3x3):\n{D.toarray()}")

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [44]:
# Example 39: Triangular Matrix
A = np.array([[1, 2, 3], [0, 4, 5], [0, 0, 6]])
B = linalg.tril(A)
C = linalg.triu(A)
print(f"A:\n{A}")
print(f"Lower Triangular Matrix (B):\n{B}")
print(f"Upper Triangular Matrix (C):\n{C}")

A:
[[1 2 3]
 [0 4 5]
 [0 0 6]]
Lower Triangular Matrix (B):
[[1 0 0]
 [0 4 0]
 [0 0 6]]
Upper Triangular Matrix (C):
[[1 2 3]
 [0 4 5]
 [0 0 6]]


In [45]:
# Example 40: Matrix Exponential of Symmetric Matrix
A = np.array([[1, 2], [2, 3]])
exp_A = linalg.expm(A)
print(f"A:\n{A}")
print(f"e^A (Matrix Exponential of Symmetric Matrix):\n{exp_A}")

A:
[[1 2]
 [2 3]]
e^A (Matrix Exponential of Symmetric Matrix):
[[19.68002699 30.56514746]
 [30.56514746 50.24517445]]


In [46]:
# Example 41: Moore-Penrose Pseudoinverse
A = np.array([[1, 2], [3, 4], [5, 6]])
pinv_A = linalg.pinv(A)
print(f"A:\n{A}")
print(f"Moore-Penrose Pseudoinverse of A:\n{pinv_A}")

A:
[[1 2]
 [3 4]
 [5 6]]
Moore-Penrose Pseudoinverse of A:
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [47]:
# Example 42: Matrix Trace
A = np.array([[1, 2], [3, 4]])
trace_A = np.trace(A)
print(f"A:\n{A}")
print(f"Trace of A: {trace_A}")

A:
[[1 2]
 [3 4]]
Trace of A: 5


In [48]:
# Example 43: Normalized Matrix Norm
A = np.array([[1, 2], [3, 4]])
norm_A = linalg.norm(A, 'fro')
print(f"A:\n{A}")
print(f"Normalized Frobenius Norm of A: {norm_A}")

A:
[[1 2]
 [3 4]]
Normalized Frobenius Norm of A: 5.477225575051661


In [49]:
# Example 44: Condition Number
A = np.array([[1, 2], [3, 4]])
cond_num = linalg.cond(A)
print(f"A:\n{A}")
print(f"Condition Number of A: {cond_num}")

AttributeError: module 'scipy.linalg' has no attribute 'cond'

In [50]:
# Example 45: LU Factorization with Permutation
A = np.array([[1, 2], [3, 4]])
P, L, U = linalg.lu(A)
print(f"A:\n{A}")
print(f"P (Permutation Matrix):\n{P}")
print(f"L (Lower Triangular Matrix):\n{L}")
print(f"U (Upper Triangular Matrix):\n{U}")

A:
[[1 2]
 [3 4]]
P (Permutation Matrix):
[[0. 1.]
 [1. 0.]]
L (Lower Triangular Matrix):
[[1.         0.        ]
 [0.33333333 1.        ]]
U (Upper Triangular Matrix):
[[3.         4.        ]
 [0.         0.66666667]]


In [51]:
# Example 46: Matrix Inversion using LU Factorization with Permutation
A = np.array([[1, 2], [3, 4]])
P, L, U = linalg.lu(A)
A_inv = linalg.inv(U) @ linalg.inv(L) @ linalg.inv(P)
print(f"A:\n{A}")
print(f"Inverse of A using LU Factorization with Permutation:\n{A_inv}")

A:
[[1 2]
 [3 4]]
Inverse of A using LU Factorization with Permutation:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [52]:
# Example 47: QR Decomposition with Column Pivoting
A = np.array([[1, 2], [3, 4], [5, 6]])
Q, R, P = linalg.qr(A, pivoting=True)
print(f"A:\n{A}")
print(f"Q (Unitary matrix):\n{Q}")
print(f"R (Upper Triangular Matrix):\n{R}")
print(f"P (Permutation Matrix):\n{P}")

A:
[[1 2]
 [3 4]
 [5 6]]
Q (Unitary matrix):
[[-0.26726124  0.87287156  0.40824829]
 [-0.53452248  0.21821789 -0.81649658]
 [-0.80178373 -0.43643578  0.40824829]]
R (Upper Triangular Matrix):
[[-7.48331477 -5.87974732]
 [ 0.         -0.65465367]
 [ 0.          0.        ]]
P (Permutation Matrix):
[1 0]


In [53]:
# Example 48: Sparse Linear System Solver (Iterative Method)
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
b = np.array([1, 2, 3])
x, _ = sparse_linalg.bicgstab(A, b)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector b: {b}")
print(f"Solutions of Ax = b using BiCGSTAB: {x}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [54]:
# Example 49: Sparse Matrix Eigenvalues and Eigenvectors
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
eigenvalues, eigenvectors = sparse_linalg.eigs(A, k=2)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Eigenvalues:\n{eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [55]:
# Example 50: Sparse Matrix Determinant
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
det = sparse_linalg.det(A)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Determinant of A: {det}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'