In [29]:
import numpy as np
import scipy.linalg as linalg
import scipy.sparse.linalg as sparse_linalg
import scipy

In [2]:
# Example 1: Matrix Inversion using LU Decomposition
A = np.array([[1, 2], [3, 4]])
B = linalg.inv(A)
print(f"Inverse of A:\n{B}")

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [3]:
# Example 2: LU Decomposition
P, L, U = linalg.lu(A)
print(f"P:\n{P}")
print(f"L:\n{L}")
print(f"U:\n{U}")

P:
[[0. 1.]
 [1. 0.]]
L:
[[1.         0.        ]
 [0.33333333 1.        ]]
U:
[[3.         4.        ]
 [0.         0.66666667]]


In [4]:
# Example 3: QR Decomposition
Q, R = linalg.qr(A)
print(f"Q:\n{Q}")
print(f"R:\n{R}")

Q:
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R:
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [5]:
# Example 4: Singular Value Decomposition (SVD)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
U, s, Vh = linalg.svd(A)
print(f"U:\n{U}")
print(f"Singular Values:\n{s}")
print(f"Vh:\n{Vh}")


U:
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Singular Values:
[1.68481034e+01 1.06836951e+00 4.41842475e-16]
Vh:
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [6]:
# Example 5: Solving Linear System using LU Decomposition
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 11])
x = linalg.solve(A, b)
print(f"x:\n{x}")

x:
[1. 2.]


In [7]:
# Example 6: Solving Linear System using QR Decomposition
Q, R = linalg.qr(A)
b = np.array([5, 11])
y = np.dot(Q.T, b)
x = linalg.solve_triangular(R, y)
print(f"x:\n{x}")

x:
[1. 2.]


In [8]:
# Example 7: Iterative Solver (Conjugate Gradient Method)
A = np.array([[4, -1, 1], [-1, 4, -2], [1, -2, 3]])
b = np.array([6, 3, 4])
x, _ = sparse_linalg.cg(A, b)
print(f"x:\n{x}")

x:
[1.48275862 2.31034483 2.37931034]


In [9]:
# Example 8: Iterative Solver (BiCGSTAB Method)
A = np.array([[4, -1, 1], [-1, 4, -2], [1, -2, 3]])
b = np.array([6, 3, 4])
x, _ = sparse_linalg.bicgstab(A, b)
print(f"x:\n{x}")


x:
[1.48275862 2.31034483 2.37931034]


In [16]:
# Example 9: Sparse Matrix Creation (CSC Format)
import scipy.sparse

rows = np.array([0, 1, 1, 2, 2, 2])
cols = np.array([0, 0, 1, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
A = linalg.csc_matrix((data, (rows, cols)), shape=(3, 3))
print(f"Sparse Matrix (CSC Format):\n{A.toarray()}")

AttributeError: module 'scipy.linalg' has no attribute 'csc_matrix'

In [11]:
# Example 10: Sparse Matrix Creation (COO Format)
rows = np.array([0, 1, 1, 2, 2, 2])
cols = np.array([0, 0, 1, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
A = linalg.coo_matrix((data, (rows, cols)), shape=(3, 3))
print(f"Sparse Matrix (COO Format):\n{A.toarray()}")

AttributeError: module 'scipy.linalg' has no attribute 'coo_matrix'

In [13]:
# Example 11: Sparse Matrix Creation (CSR Format)
rows = np.array([0, 1, 1, 2, 2, 2])
cols = np.array([0, 0, 1, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
A = linalg.csr_matrix((data, (rows, cols)), shape=(3, 3))
print(f"Sparse Matrix (CSR Format):\n{A.toarray()}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [14]:
# Example 12: Sparse Matrix Vector Multiplication
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
x = np.array([1, 2, 3])
b = A.dot(x)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector x: {x}")
print(f"Result of A*x: {b}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [15]:
# Example 13: Sparse Matrix Addition
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
B = linalg.csr_matrix([[3, 0, 1], [0, 2, 0], [2, 0, 4]])
C = A + B
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Sparse Matrix B:\n{B.toarray()}")
print(f"Result of A + B:\n{C.toarray()}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [17]:
# Example 14: Sparse Matrix Subtraction
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
B = linalg.csr_matrix([[3, 0, 1], [0, 2, 0], [2, 0, 4]])
C = A - B
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Sparse Matrix B:\n{B.toarray()}")
print(f"Result of A - B:\n{C.toarray()}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [18]:
# Example 15: Sparse Matrix Multiplication
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
B = linalg.csr_matrix([[3, 0, 1], [0, 2, 0], [2, 0, 4]])
C = A.dot(B)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Sparse Matrix B:\n{B.toarray()}")
print(f"Result of A * B:\n{C.toarray()}")


AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [19]:
# Example 16: Sparse Matrix Transpose
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
B = A.transpose()
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Sparse Matrix A Transpose:\n{B.toarray()}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [20]:
# Example 17: Sparse Matrix Inversion
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
A_inv = sparse_linalg.inv(A)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Inverse of A:\n{A_inv.toarray()}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [21]:
# Example 18: Sparse Matrix Determinant
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
det = sparse_linalg.det(A)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Determinant of A: {det}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [22]:
# Example 19: Sparse Matrix Eigenvectors and Eigenvalues
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
eigenvalues, eigenvectors = sparse_linalg.eigs(A, k=2)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Eigenvalues:\n{eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [23]:
# Example 20: Sparse Linear System Solver
A = linalg.csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 5]])
b = np.array([1, 2, 3])
x = sparse_linalg.spsolve(A, b)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector b: {b}")
print(f"Solutions of Ax = b: {x}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [24]:
# Example 21: Sparse Matrix Tridiagonal System Solver
diagonals = [[1, 2, 3], [4, 5, 6, 7], [8, 9, 10]]
A = linalg.spdiags(diagonals, [-1, 0, 1], 4, 4)
b = np.array([1, 2, 3, 4])
x = sparse_linalg.spsolve(A, b)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector b: {b}")
print(f"Solutions of Ax = b: {x}")

AttributeError: module 'scipy.linalg' has no attribute 'spdiags'

In [25]:
# Example 22: Iterative Linear Solver for Sparse Matrix
A = linalg.csr_matrix([[4, -1, 0], [-1, 4, -1], [0, -1, 4]])
b = np.array([3, 4, 3])
x, _ = sparse_linalg.cg(A, b)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector b: {b}")
print(f"Solutions of Ax = b using CG: {x}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [26]:
# Example 23: Iterative Linear Solver for Sparse Matrix (BiCGSTAB)
A = linalg.csr_matrix([[4, -1, 0], [-1, 4, -1], [0, -1, 4]])
b = np.array([3, 4, 3])
x, _ = sparse_linalg.bicgstab(A, b)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector b: {b}")
print(f"Solutions of Ax = b using BiCGSTAB: {x}")


AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [27]:
# Example 24: Iterative Linear Solver for Sparse Matrix (GMRES)
A = linalg.csr_matrix([[4, -1, 0], [-1, 4, -1], [0, -1, 4]])
b = np.array([3, 4, 3])
x, _ = sparse_linalg.gmres(A, b)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector b: {b}")
print(f"Solutions of Ax = b using GMRES: {x}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [30]:
# Example 25: Iterative Linear Solver for Sparse Matrix (LGMRES)
A = linalg.csr_matrix([[4, -1, 0], [-1, 4, -1], [0, -1, 4]])
b = np.array([3, 4, 3])
x, _ = sparse_linalg.lgmres(A, b)
print(f"Sparse Matrix A:\n{A.toarray()}")
print(f"Vector b: {b}")
print(f"Solutions of Ax = b using LGMRES: {x}")

AttributeError: module 'scipy.linalg' has no attribute 'csr_matrix'

In [31]:
# Example 26: Cholesky Decomposition
A = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]])
L = linalg.cholesky(A)
print(f"A:\n{A}")
print(f"L (Cholesky Decomposition):\n{L}")

A:
[[  4  12 -16]
 [ 12  37 -43]
 [-16 -43  98]]
L (Cholesky Decomposition):
[[ 2.  6. -8.]
 [ 0.  1.  5.]
 [ 0.  0.  3.]]
