In [1]:
import numpy as np
import scipy.linalg as linalg
import scipy.sparse.linalg as sparse_linalg

In [2]:
# Example 1: Matrix Inversion using LU Decomposition
A = np.array([[1, 2], [3, 4]])
B = linalg.inv(A)
print(f"Inverse of A:\n{B}")

Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


In [3]:
# Example 2: LU Decomposition
P, L, U = linalg.lu(A)
print(f"P:\n{P}")
print(f"L:\n{L}")
print(f"U:\n{U}")

P:
[[0. 1.]
 [1. 0.]]
L:
[[1.         0.        ]
 [0.33333333 1.        ]]
U:
[[3.         4.        ]
 [0.         0.66666667]]


In [4]:
# Example 3: QR Decomposition
Q, R = linalg.qr(A)
print(f"Q:\n{Q}")
print(f"R:\n{R}")

Q:
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
R:
[[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [5]:
# Example 4: Singular Value Decomposition (SVD)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
U, s, Vh = linalg.svd(A)
print(f"U:\n{U}")
print(f"Singular Values:\n{s}")
print(f"Vh:\n{Vh}")


U:
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Singular Values:
[1.68481034e+01 1.06836951e+00 4.41842475e-16]
Vh:
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [6]:
# Example 5: Solving Linear System using LU Decomposition
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 11])
x = linalg.solve(A, b)
print(f"x:\n{x}")

x:
[1. 2.]
