In [2]:
# Import the NumPy library
import numpy as np

In [3]:
# print the numpy version
print(np.__version__)

1.24.2


In [4]:
# Creating NumPy arrays
input_array = np.array([11, 22, 33, 44, 55])
print(input_array)

[11 22 33 44 55]


In [5]:
# Array shape and size
print("Shape of the input_array is :", input_array.shape)
print("Size of the input_array is :", input_array.size)

Shape of the input_array is : (5,)
Size of the input_array is : 5


In [6]:
# Accessing Elements in the array.
print("The First element in the input_array is :", input_array[0])
print("The Last element in the input_array is :", input_array[-1])
print("Slicing the elements from the input_array :", input_array[2:4])

The First element in the input_array is : 11
The Last element in the input_array is : 55
Slicing the elements from the input_array : [33 44]


In [7]:
# Operations on the input_array
second_input_array = np.array([66, 77, 88, 99, 100])
print("Addition on Two Input Arrays :", input_array + second_input_array)
print("Subtraction on Two Input Arrays  :", input_array  - second_input_array)
print("Multiplication on Two Input Arrays  :", input_array  * second_input_array)
print("Division on Two Input Arrays :", input_array  / second_input_array)

Addition on Two Input Arrays : [ 77  99 121 143 155]
Subtraction on Two Input Arrays  : [-55 -55 -55 -55 -45]
Multiplication on Two Input Arrays  : [ 726 1694 2904 4356 5500]
Division on Two Input Arrays : [0.16666667 0.28571429 0.375      0.44444444 0.55      ]


In [8]:
# Applying Basic Function on the input arrays
print("Minimum ELement in the input_array :", np.min(input_array))
print("Maximum Element in the input_array :", np.max(input_array))
print("Sum of Elements in the input_array :", np.sum(input_array))
print("Mean of Elemenets in the input_array :", np.mean(input_array))
print("Standard Deviation of Elements in the input_array:", np.std(input_array))

Minimum ELement in the input_array : 11
Maximum Element in the input_array : 55
Sum of Elements in the input_array : 165
Mean of Elemenets in the input_array : 33.0
Standard Deviation of Elements in the input_array: 15.556349186104045


In [9]:
input_array = np.array([1, 2, 3, 4])
print(input_array.ndim)

input_array_multi = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(input_array_multi.ndim)
print("The Value of input_array_multi is :: \n ",input_array_multi)

print("Size of the Array in Bytes :: ",input_array_multi.itemsize,"bytes") 
print("Data Type of elements in the Array :: ",input_array_multi.dtype) 
print("The Size of the array is :: ",input_array_multi.size)  
print("The Shape of the array is :: ",input_array_multi.shape)  

1
2
The Value of input_array_multi is :: 
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Size of the Array in Bytes ::  4 bytes
Data Type of elements in the Array ::  int32
The Size of the array is ::  12
The Shape of the array is ::  (3, 4)


In [ ]:
# Check the data type of the array

string_array = np.array(['apple', 'banana', 'cherry'])
print("The data type of the array is ::",string_array.dtype)
numeric_array = np.array([1, 2, 3, 4])

In [10]:
# Find Maximukm Minimum ELements and sum of elements in the array

print("The maximum element in the input_array_multi is :: ",input_array_multi.max())  
print("The minimum element in the input_array_multi is :: ",input_array_multi.min())  
print("The sum of the elements in the input_array_multi is :: ",input_array_multi.sum()) 

The maximum element in the input_array_multi is ::  12
The minimum element in the input_array_multi is ::  1
The sum of the elements in the input_array_multi is ::  78
