In [1]:
import numpy as np

In [3]:
# reshaping the array using the function reshape
input_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:")
print(input_array)
print("Reshaped array:")
print(input_array.reshape(3, 2))

Original array:
[[1 2 3]
 [4 5 6]]
Reshaped array:
[[1 2]
 [3 4]
 [5 6]]


In [5]:
# Demonstrating array concatenation using concatenate function in numpy and displaying the array.
input_array_1 = np.array([1, 2, 3])
input_array_2 = np.array([4, 5, 6])
print("Concatenated array:", np.concatenate((input_array_1, input_array_2)))

Concatenated array: [1 2 3 4 5 6]


In [8]:
# Demonstating of Stacking : Horizondal Stacking and Vertical Stacking using Numpy Arrays.
input_array_3 = np.array([[1, 2], [3, 4]])
input_array_4 = np.array([[5, 6], [7, 8]])
print("Output-Vertical-Stacking : ")
print(np.vstack((input_array_3, input_array_4)))
print("Output-Horizontal-Stacking : ")
print(np.hstack((input_array_3, input_array_4)))

Output-Vertical-Stacking : 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Output-Horizontal-Stacking : 
[[1 2 5 6]
 [3 4 7 8]]
