In [1]:
import numpy as np

In [3]:
# reshaping the array using the function reshape
input_array = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:")
print(input_array)
print("Reshaped array:")
print(input_array.reshape(3, 2))

Original array:
[[1 2 3]
 [4 5 6]]
Reshaped array:
[[1 2]
 [3 4]
 [5 6]]


In [5]:
# Demonstrating array concatenation using concatenate function in numpy and displaying the array.
input_array_1 = np.array([1, 2, 3])
input_array_2 = np.array([4, 5, 6])
print("Concatenated array:", np.concatenate((input_array_1, input_array_2)))

Concatenated array: [1 2 3 4 5 6]


In [8]:
# Demonstating of Stacking : Horizondal Stacking and Vertical Stacking using Numpy Arrays.
input_array_3 = np.array([[1, 2], [3, 4]])
input_array_4 = np.array([[5, 6], [7, 8]])
print("Output-Vertical-Stacking : ")
print(np.vstack((input_array_3, input_array_4)))
print("Output-Horizontal-Stacking : ")
print(np.hstack((input_array_3, input_array_4)))

Output-Vertical-Stacking : 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Output-Horizontal-Stacking : 
[[1 2 5 6]
 [3 4 7 8]]


In [10]:
# Broadcasting of Arrays using Numpy
input_array_5 = np.array([1, 2, 3])
scalar_value = 2
print("output-Broadcasting : ")
print(input_array_5 + scalar_value)

output-Broadcasting : 
[3 4 5]


In [12]:
# Demonstration of array indexing and slicing ( Accesing elements in rows and columns )
input_array_6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("The Element at (1, 2) : ", input_array_6[1, 2])
print("The First column Elements are : ", input_array_6[:, 0])
print("The Last row Elements are : ", input_array_6[-1, :])

The Element at (1, 2) :  6
The First column Elements are :  [1 4 7]
The Last row Elements are :  [7 8 9]


In [14]:
# Boolean Indexing using Numpy
input_array_7 = np.array([1, 2, 3, 4, 5])
print("Elements greater than 3 are :", input_array_7[input_array_7 > 3])

Elements greater than 3 are : [4 5]


In [15]:
# Random Number Generation using Numpy
array_create_random = np.random.rand(3, 3)
print("Array Created using random Elements are :")
print(array_create_random)

Array Created using random Elements are :
[[0.43271041 0.89297482 0.64259628]
 [0.69570878 0.53125741 0.82568157]
 [0.11910471 0.64031321 0.07275964]]


In [16]:
# We can save and Load the arrays using numpy lib
np.save("array_create_random", array_create_random)
loaded_array_content = np.load("array_create_random.npy")
print("Load the Stored array from the file :")
print(loaded_array_content)

Load the Stored array from the file :
[[0.43271041 0.89297482 0.64259628]
 [0.69570878 0.53125741 0.82568157]
 [0.11910471 0.64031321 0.07275964]]
