In [1]:
import numpy as np

In [3]:
# Indexing and Slicing with Boolean Arrays:
input_array = np.array([1, 2, 3, 4, 5])
boolean_array = np.array([True, False, True, False, True])
print("Elements where bool_arr is True:", input_array[boolean_array])

Elements where bool_arr is True: [1 3 5]


In [5]:
# Broadcasting allows for arithmetic operations between arrays of different shapes. 
input_array_2 = np.array([1, 2, 3])
input_array_3 = np.array([[1], [2], [3]])
print("Broadcasted array : ")
print(input_array_2 + input_array_3)

Broadcasted array : 
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [7]:
# Calculate Matrix Multiplications and Transpose
input_array_4 = np.array([[1, 2], [3, 4]])
input_array_5 = np.array([[5, 6], [7, 8]])
print("Matrix multiplication:")
print(np.dot(input_array_4, input_array_5))
print("Matrix transpose:")
print(input_array_4.T)

Matrix multiplication:
[[19 22]
 [43 50]]
Matrix transpose:
[[1 3]
 [2 4]]


In [8]:
# Demonstratioon of Universional Functions :: Square Root on Individual Elements.
inopyt_array_6 = np.array([1, 2, 3, 4, 5])
print("Square root of each element:")
print(np.sqrt(inopyt_array_6))

Square root of each element:
[1.         1.41421356 1.73205081 2.         2.23606798]


In [9]:
# Masking of Arrays 
input_array_7 = np.array([1, 2, 3, 4, 5])
mask = input_array_7 > 3
print("Output of the Masked array:")
print(input_array_7[mask])

Output of the Masked array:
[4 5]


In [ ]:
# Saving the contents of the arrays as text file 

input_array_8 = np.array([1, 2, 3, 4, 5])
np.savetxt("array_save_content.txt", input_array_8)
loaded_input = np.loadtxt("array_save_content.txt")
print("Loaded array from file:")
print(loaded_input)